### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Daniduran-dev**
In this project, I try to recreate some of the most common Ruby Enumerable methods.

I've been testing it in the way the Microverse curriculum says it should be tested for Ruby beginners. I used "put [1, 2, 3, 4, 5].my_each { |x| x + 1 }, for example.
Please, if you find that the code doesn't work as it is supposed to try to be clear with the test that you have been using and try to give me your test to me so I can test my code in the "puts ---------- " format for beginners, not Rspec, please. Otherwise, give me your contact and we can arrange a video call so you can explain to me how to test the code. What it cant happen is that I get a review but I don't know what are the errors because I can't pass those tests. That's like coding blindfolded.
Thank you.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required. 
Great progress in this project.
I will give a detailed review about the expected behavior of the methods versus what we have in our own version of the methods.

### REQUIRED
**#my_each**
* When a block is given when self is a hash behaves like #each calls the given block once for each element in self.

**#my_all?**
* When no block or argument is given returns true when none of the collection members are false or nil.
Screenshot from 2020-07-23 22-31-46
* When a class is passed as an argument returns true if all of the collection is a member of such class::Integer.
Screenshot from 2020-07-23 22-35-23
* When a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
Screenshot from 2020-07-23 22-37-33

**#my_any?**
* Returns false if the block ever returns a value false or nil
Screenshot from 2020-07-23 22-42-00
* When a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
Screenshot from 2020-07-23 22-44-49
* When a Regex is passed as an argument returns false if none of the collection matches the Regex.
Screenshot from 2020-07-23 22-47-31
* When a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern.
Screenshot from 2020-07-23 22-52-08

**#my_none?**
* Returns true if the block never returns true for all elements.
Screenshot from 2020-07-23 22-56-04
* When a Regex is passed as an argument returns true if none of the collection matches the Regex.
Screenshot from 2020-07-23 22-59-12
* When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern.
Screenshot from 2020-07-23 23-00-59

**#my_inject**
* Raises a "LocalJumpError" when no block or argument is given.
Screenshot from 2020-07-23 23-03-16


**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

**Comment by wathigo** [comment]
> ### Please submit the review request using the same pull request as the previous review to make the process more efficient.

**Comment by Daniduran-dev** [comment]
Hello,

I've been trying to use another thing than the case equality operator but I'm unable to find a solution. If that's a requirement for the project to be approved please help me out with this.. what can I use instead of === ? I've been trying with is_a? kind_of? instance_of? and == but nothing works.

Thank you

**Comment by rOluochKe** [comment]
Read these 2 articles:-
- https://medium.com/rubyinside/triple-equals-black-magic-d934936a6379
- https://blog.arkency.com/the-equals-equals-equals-case-equality-operator-in-ruby/

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Daniduran-dev 
### Your methods are passing tests :clap: the only problem you have is to fix the linting errors being shown in the pr
### Make the changes and submit for another review. Good luck
- Happy coding!

**Comment by Daniduran-dev** [comment]
Thank you I'm going to read them now!

**Comment by Daniduran-dev** [comment]
Hello,
I've been trying to fix the rubocop errors. The last TSE gave me some links to check how to do it. I just can fix one of them.. the one that remains behave in a weird way... I've been trying for so long but impossible to find a solution. Do you have a solution or know someone that knows how to do this? Please teach me. Thank you.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Daniduran-dev, great job with this project :+1: Great job fixing the linter errors :100: However, let us fix the rubocop errors before we get our project approved.
Kindly check the screenshot below
rub

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Daniduran-dev** [comment]
Hello,
There's a (silly) rubocop problem here. The local rubocop and the github rubocop tell me to fix different things. The real conflict is that when I fix the things that the local rubocop tells me to fix then github rubocop says it is wrong. If this has to be changed just you microverse people decide what rubocop prevails local or github? Than you for your help.

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

Thank you for applying the changes.
You can merge it :+1: 

Good continuation :handshake: 

Mael FOSSO

**Pull request merged**
